kitten-science/kitten-scientists

- packages/userscript/source/settings/Settings.ts
- packages/userscript/source/ui/components/Fieldset.ts
- packages/userscript/source/ui/components/OptionsListItem.ts
- packages/userscript/source/ui/components/RadioItem.ts
This allows us to build UI where we provide a set of options and the user can select one of the options.
> feat(ui): Add support for radio groups

- packages/userscript/source/BonfireManager.ts
I ran into a condition in the fast-paragon experiments where all of the conditions in KS to push the aqueduct-to-hydroplant button were met, but the mustExist(getBuildButton(aqueduct)) failed. I think there is another condition before the game makes the upgrade button available. It might be having at least one miner, but I'm not exactly sure. For safety I added try/catch blocks around all of the bonfire upgrade operations. The catch just prints a console warning if the upgrade fails and KS should try it again in a future tick.
> Add try-catch around bonfire upgrade button presses

- packages/userscript/source/ui/UserInterface.ts
On the default theme, the UI is hard to use, because the scrollbar overlays the expando buttons on hover.
> fix(ui): Scrollbar overlays expando buttons

- packages/userscript/source/TimeControlManager.ts
The stock value configured for temporal flux was ignored. Now, tempus fugit is stopped to preserve temporal flux as configured.
Fixes #83
> fix(time): Accelerate time goes below stock

- packages/userscript/source/settings/ElectLeaderSettings.ts
- packages/userscript/source/settings/Settings.ts
- packages/userscript/source/types/index.ts
Some jobs and traits, when selected as leader, would not have any effect.
Fixes https://github.com/kitten-science/kitten-scientists/issues/104
> fix(village): Not all jobs/traits are assigned as leaders

- .github/workflows/release-info.yml
- .github/workflows/userscript-nightly.yml
- .github/workflows/userscript-publish.yml
- packages/action-release-info/action.yml
- packages/action-release-info/package.json
- packages/action-release-info/source/ReleaseInfo.mts
- packages/action-release-info/source/main.mts
- packages/action-release-info/tsconfig.json
- yarn.lock
We now publish a metadata file that contains information about the different KS releases. This could later be used to indicate available updates to users.
> ci: Generate release info

- packages/documentation/docs/sections/bonfire.md
- packages/documentation/docs/sections/village.md
- packages/documentation/docs/sections/workshop.md
- packages/documentation/mkdocs.yml
- packages/userscript/source/WorkshopManager.ts
- packages/userscript/source/settings/WorkshopSettings.ts
- packages/userscript/source/ui/WorkshopSettingsUi.ts
There was some edge case handling to balance production between plates and steel, which seems entirely redundant, given the balancing behavior of limited crafting.
The trigger applied to some hardcoded material, only a single one, and only for some crafts. This could cause unintuitive crafting behavior.
Even if the trigger wasn't hit, a resource could still be crafted under certain conditions.
The behavior of limited crafting was inconsistent.
The way resource crafting behaves now, should be far more intuitive and consistent. Additionally, it has now been documented.
> feat(workshop): Simplify resource crafting

- .vscode/settings.json
- packages/userscript/source/WorkshopManager.ts
- packages/userscript/source/helper/BulkPurchaseHelper.ts
- packages/userscript/source/settings/BonfireSettings.ts
- packages/userscript/source/settings/ReligionSettings.ts
- packages/userscript/source/settings/TimeSettings.ts
Previously, builds would optionally define a single required resource. This resource would be the only one taken into consideration for the trigger value.
Now, this hardcoded requirement has been removed and the trigger applies to all source materials that have a capacity.
> feat(core): Remove hardcoded build requirements

- packages/userscript/source/settings/BonfireSettings.ts
- packages/userscript/source/settings/BuildingUpgradeSettings.ts
- packages/userscript/source/settings/EmbassySettings.ts
- packages/userscript/source/settings/LogFilterSettings.ts
- packages/userscript/source/settings/MissionSettings.ts
- packages/userscript/source/settings/PolicySettings.ts
- packages/userscript/source/settings/ReligionSettings.ts
- packages/userscript/source/settings/ResetBonfireSettings.ts
- packages/userscript/source/settings/ResetReligionSettings.ts
- packages/userscript/source/settings/ResetResourcesSettings.ts
- packages/userscript/source/settings/ResetSpaceSettings.ts
- packages/userscript/source/settings/ResetTimeSettings.ts
- packages/userscript/source/settings/ResourcesSettings.ts
- packages/userscript/source/settings/SpaceSettings.ts
- packages/userscript/source/settings/TechSettings.ts
- packages/userscript/source/settings/TimeSettings.ts
- packages/userscript/source/settings/TradeSettings.ts
- packages/userscript/source/settings/UpgradeSettings.ts
- packages/userscript/source/settings/WorkshopSettings.ts
State snapshots now contain only your settings. Previously, they would also contain internals, that shouldn't be modified anyway.
The size of state snapshots has been reduced from ~34KB to ~17KB, about 50% smaller.
> feat(core): Remove redundant state fields

- packages/userscript/source/TimeManager.ts
The internal search for the right button model was imprecise. It would look at the model for the "Fix Cryochambers" button, instead of the Cryochambers one, because the name was similar enough.
Fixes #117
> fix(time): Cryochambers are not built

- packages/userscript/source/ReligionManager.ts
Scientists would attempt to refine tears -> BLS even when BLS was at its max. They would repeatedly fail, and everyone would be sad.
This commit makes the scientists refine tears only when BLS is below max.
> fix(religion): Only try crafting BLS up to max

- packages/userscript/source/WorkshopManager.ts
The consume rate was only applied to resources that have a capacity. The behavior also felt entirely inconsistent. Now, the consume rate is applied consistently, whenever a part of KS requests to know how much of a resource is available for use.
> fix(workshop): Consume rate not applied consistently

- packages/documentation/docs/sections/time-control.md
- packages/kitten-scientists/source/TimeControlManager.ts
- packages/kitten-scientists/source/settings/TimeSkipSettings.ts
- packages/kitten-scientists/source/ui/TimeSkipSettingsUi.ts
KS will usually not combust TCs when you have accumulated too much chrono heat, as those combustions cost a premium. This options allows you to override that behavior, when skipping time is more important than preserving TCs.
Fixes #18
> feat(time): Allow ignoring overheating for time skip

- packages/kitten-scientists/source/Engine.ts
skip rebuildUI in Engine constructor.
calling UserScript.rebuildUI in the constructor causing circular dependencies issue, since the Engine is needed for rebuildUI.
skip rebuildUI when setLanguage in the engine constructor, it will then set it again in stateLoad and call rebuildUI if needed.
fix #232
> fix(core): Can't start when using non-English language

- packages/kitten-scientists/source/TradeManager.ts
Previously, setting any season filter for a race had no effect at all.
Fixes #210
> fix(trade): Season selection is ignored

- packages/kitten-scientists/source/ReligionManager.ts
- packages/kitten-scientists/source/types/index.ts
Because we were only "clicking" the regular sacrifice button every iteration, we would always only sacrifice 2500 unicorns. But players often spawn far more unicorns than that in the same time, making them grow infinitely.
Fixes #192
> fix(religion): Unicorns are sacrificed too slowly

- packages/kitten-scientists/package.json
- packages/kitten-scientists/source/UserScript.ts
- packages/kitten-scientists/source/state/State.ts
- packages/kitten-scientists/source/state/StateLoader.ts
- packages/kitten-scientists/source/state/StateMerger.ts
- schemas/.scripts/load-profile.js
- yarn.lock
Can currently be tested with:
```js
kittenScientists.importSettingsFromUrl("https://kitten-science.com/presets/experiment.json")
```
> Settings Profiles

- packages/kitten-scientists/source/ReligionManager.ts
- packages/kitten-scientists/source/i18n/en.json
- packages/kitten-scientists/source/types/index.ts
- packages/kitten-scientists/source/types/religion.ts
Sacrificing unicorns, sacrificing alicorns, refining tears, and refining TCs, are now all handled in bulk.
Fixes #584
> feat(religion): Bulk process Ziggurats resources

- packages/kitten-scientists/source/BonfireManager.ts
- packages/kitten-scientists/source/ReligionManager.ts
- packages/kitten-scientists/source/SpaceManager.ts
- packages/kitten-scientists/source/TimeControlManager.ts
- packages/kitten-scientists/source/TimeManager.ts
- packages/kitten-scientists/source/TradeManager.ts
- packages/kitten-scientists/source/VillageManager.ts
- packages/kitten-scientists/source/WorkshopManager.ts
- packages/kitten-scientists/source/helper/BulkPurchaseHelper.ts
- packages/kitten-scientists/source/tools/Format.ts
Many purchasing mechanisms in KS are driven by the "Bulk Purchase Helper". This component receives build requests, and is then expected to figure out how many items to build out of those requests. The helper works well enough, but has certain negative behaviors that most KS users will likely be aware of:
1. Build requests are always in the same order, as they are derived from your settings, which have a fixed order. The result is that certain items are _always_ built before other items. You will notice that certain buildings will only be built if another building becomes more expensive than itself.
2. When KS orders a large amount of certain items, a single build request can consume so many resources that no other build request can be satisfied. This can be especially painful after resets …
> feat(core): Implement new bulk purchase strategy

- packages/kitten-scientists/source/settings/ReligionSettings.ts
- packages/kitten-scientists/source/settings/ResetBonfireSettings.ts
- packages/kitten-scientists/source/settings/ResetReligionSettings.ts
- packages/kitten-scientists/source/settings/ResetSpaceSettings.ts
- packages/kitten-scientists/source/settings/ResetTimeSettings.ts
- packages/kitten-scientists/source/settings/Settings.ts
- packages/kitten-scientists/source/settings/TradeSettings.ts
- packages/kitten-scientists/source/ui/ReligionSettingsUi.ts
- packages/kitten-scientists/source/ui/TimeSkipHeatSettingsUi.ts
- packages/kitten-scientists/source/ui/TimeSkipSettingsUi.ts
- packages/kitten-scientists/source/ui/TradeSettingsUi.ts
- packages/kitten-scientists/source/ui/components/SettingBuySellTriggerListItem.ts
- packages/kitten-scientists/source/ui/components/SettingTriggerListItem.ts
- packages/kitten-scientists/source/ui/components/buttons-icon/TriggerButton.ts
Some of our triggers are expressed as percentage, some as an absolute value. Developers always had to carefully the correct handler for the given kind of trigger. This was cumbersome and error-prone.
We now introduce a new data structure to handle this kinds of triggers more intuitively and without explicit selection.
Fixes #627
> fix(core): Inconsistent trigger handling

- packages/kitten-scientists/source/TimeManager.ts
- packages/kitten-scientists/source/i18n/en-US.json
- packages/kitten-scientists/source/settings/TimeSettings.ts
- packages/kitten-scientists/source/ui/TimeSettingsUi.ts
Always turning on Chrono Furnaces is counter-productive in most scenarios. This is superseded by better automations in the Time Control section.
> feat(time): Remove Chrono Furnace automation

- packages/kitten-scientists/source/TimeControlManager.ts
- packages/kitten-scientists/source/ui/TimeSkipHeatSettingsUi.module.css
- packages/kitten-scientists/source/ui/TimeSkipHeatSettingsUi.ts
- packages/kitten-scientists/source/ui/UserInterface.module.css
When Active Heat Transfer is currently actively transferring heat, you will now see an animated indicator next to it.
In case this is unclear, Active Heat Transfer prevents time skips during this period, until all the chrono heat has been transferred into furnaces.
> feat(ui): Indicate when Active Heat Transfer is active

- packages/kitten-scientists/source/ReligionManager.ts
- packages/kitten-scientists/source/settings/ReligionSettings.ts
- packages/kitten-scientists/source/ui/ReligionSettingsUi.ts
- packages/kitten-scientists/source/ui/components/Button.module.css
When the build order for unicorn buildings is automated, we now display the building that we're focusing on.
Fixes: #740
> feat(ui): Highlight the next best unicorn building

- Makefile
Changed mkdir --parents option to mkdir -p
Fixes #953
> fix: Makefile compatibility with Mac

- Makefile
- source/KittenScientists.ts
- source/entrypoint-loader.ts
- vite.config.inject.js
- vite.config.loader.js
Ideally, by always only performing a very thin injection of a `script` node into the DOM, just like with the bookmarklet, we can unify all script loading approaches, and potentially solve GreaseMonkey integration issues.
Initial testing confirms that the new loader works with GreaseMonkey.
> feat: Unified script loader
